version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.9.0
  browser-tools: circleci/browser-tools@dev:alpha
  jq: circleci/jq@1.7.0

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  machine:
    machine: true

  macos:
    macos:
      xcode: "10.2.0"

  docker:
    resource_class: small
    docker:
      - image: node

  ci-docker:
    resource_class: small
    docker:
      - image: circleci/node:boron

jobs:
  test:
    parameters:
      executor:
        type: executor

      firefox-version:
        type: string
        default: latest

      geckodriver-version:
        type: string
        default: latest

    executor: <<parameters.executor>>

    steps:
      - jq/install

      - browser-tools/install-firefox:
          version: <<parameters.firefox-version>>

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    test-master
  ]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/browser-tools
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: d5:f2:f8:4b:91:76:27:e6:09:2b:ad:06:ac:8f:fa:3e
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          cleanup-tags: true
          ssh-fingerprints: d5:f2:f8:4b:91:76:27:e6:09:2b:ad:06:ac:8f:fa:3e
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # alpine
      - test:
          name: test-latest-alpine-dev
          executor: ci-base
          filters: *integration-dev_filters

      - test:
          name: test-older-alpine-dev
          executor: ci-base
          firefox-version: "66.0.3"
          # geckodriver-version: v0.23.0
          filters: *integration-dev_filters

      # machine
      - test:
          name: test-latest-machine-dev
          executor: machine
          filters: *integration-dev_filters

      - test:
          name: test-older-machine-dev
          executor: machine
          firefox-version: "65.0.1"
          # geckodriver-version: v0.22.0
          filters: *integration-dev_filters

      # mac
      - test:
          name: test-latest-mac-dev
          executor: macos
          filters: *integration-dev_filters

      - test:
          name: test-older-mac-dev
          executor: macos
          firefox-version: "64.0"
          # geckodriver-version: v0.21.0
          filters: *integration-dev_filters

      # docker
      - test:
          name: test-latest-docker-dev
          executor: docker
          filters: *integration-dev_filters

      - test:
          name: test-older-docker-dev
          executor: docker
          firefox-version: "57.0.3"
          # geckodriver-version: v0.20.1
          filters: *integration-dev_filters

      # ci-docker
      - test:
          name: test-latest-ci-docker-dev
          executor: ci-docker
          filters: *integration-dev_filters

      - test:
          name: test-older-ci-docker-dev
          executor: ci-docker
          firefox-version: "62.0.2"
          # geckodriver-version: v0.18.0
          filters: *integration-dev_filters

      # triggered by master branch commits
      - test:
          name: test-master
          executor: ci-base
          filters: *integration-master_filters
          pre-steps:
            - run: sudo rm -rf /usr/bin/jq /usr/bin/docker || true

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/browser-tools
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/browser-tools
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/browser-tools
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
