version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.10.0
  browser-tools: circleci/browser-tools@dev:alpha
  jq: circleci/jq@1.8.0

jobs:
  test:
    parameters:
      executor:
        type: executor

      firefox-version:
        type: string
        default: latest

      firefox-alpine-version:
        type: enum
        default: stable
        enum: [stable, esr]

      geckodriver-version:
        type: string
        default: latest

    executor: <<parameters.executor>>

    steps:
      - jq/install

      # - browser-tools/install-firefox:
      #     version: <<parameters.firefox-version>>
      #     alpine-version: <<parameters.firefox-alpine-version>>

      # - browser-tools/install-geckodriver:
      #     version: <<parameters.geckodriver-version>>

      - browser-tools/install-chrome

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    test-latest-alpine-master,
    test-older-alpine-master,
    test-latest-machine-master,
    test-older-machine-master,
    test-latest-mac-master,
    test-older-mac-master,
    test-latest-docker-master,
    test-older-docker-master,
    test-latest-ci-docker-master,
    test-older-ci-docker-master,
    test-latest-cimg-master,
    test-older-cimg-master
  ]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/browser-tools
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: d5:f2:f8:4b:91:76:27:e6:09:2b:ad:06:ac:8f:fa:3e
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          cleanup-tags: true
          ssh-fingerprints: d5:f2:f8:4b:91:76:27:e6:09:2b:ad:06:ac:8f:fa:3e
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # alpine
      - test:
          name: test-latest-alpine-dev
          executor: orb-tools/alpine
          filters: *integration-dev_filters

      - test:
          name: test-older-alpine-dev
          executor: orb-tools/alpine
          firefox-alpine-version: esr
          geckodriver-version: v0.23.0
          filters: *integration-dev_filters

      # machine
      - test:
          name: test-latest-machine-dev
          executor: orb-tools/machine
          filters: *integration-dev_filters

      - test:
          name: test-older-machine-dev
          executor: orb-tools/machine
          firefox-version: "65.0.1"
          geckodriver-version: v0.22.0
          filters: *integration-dev_filters

      # mac
      - test:
          name: test-latest-mac-dev
          executor: orb-tools/macos
          filters: *integration-dev_filters

      - test:
          name: test-older-mac-dev
          executor: orb-tools/macos
          firefox-version: "64.0"
          geckodriver-version: v0.21.0
          filters: *integration-dev_filters

      # docker
      - test:
          name: test-latest-docker-dev
          executor: orb-tools/node
          filters: *integration-dev_filters

      - test:
          name: test-older-docker-dev
          executor: orb-tools/node
          firefox-version: "57.0.3"
          geckodriver-version: v0.20.1
          filters: *integration-dev_filters

      # ci-docker
      - test:
          name: test-latest-ci-docker-dev
          executor: orb-tools/node-cci
          filters: *integration-dev_filters

      - test:
          name: test-older-ci-docker-dev
          executor: orb-tools/node-cci
          firefox-version: "62.0.2"
          geckodriver-version: v0.18.0
          filters: *integration-dev_filters

      # new ci-docker
      - test:
          name: test-latest-cimg-dev
          executor: orb-tools/ubuntu
          filters: *integration-dev_filters

      - test:
          name: test-older-cimg-dev
          executor: orb-tools/ubuntu
          firefox-version: "62.0.2"
          geckodriver-version: v0.18.0
          filters: *integration-dev_filters

      # triggered by master branch commits
      # alpine
      - test:
          name: test-latest-alpine-master
          executor: orb-tools/alpine
          filters: *integration-master_filters

      - test:
          name: test-older-alpine-master
          executor: orb-tools/alpine
          firefox-alpine-version: esr
          geckodriver-version: v0.23.0
          filters: *integration-master_filters

      # machine
      - test:
          name: test-latest-machine-master
          executor: orb-tools/machine
          filters: *integration-master_filters

      - test:
          name: test-older-machine-master
          executor: orb-tools/machine
          firefox-version: "65.0.1"
          geckodriver-version: v0.22.0
          filters: *integration-master_filters

      # mac
      - test:
          name: test-latest-mac-master
          executor: orb-tools/macos
          filters: *integration-master_filters

      - test:
          name: test-older-mac-master
          executor: orb-tools/macos
          firefox-version: "64.0"
          geckodriver-version: v0.21.0
          filters: *integration-master_filters

      # docker
      - test:
          name: test-latest-docker-master
          executor: orb-tools/node
          filters: *integration-master_filters

      - test:
          name: test-older-docker-master
          executor: orb-tools/node
          firefox-version: "57.0.3"
          geckodriver-version: v0.20.1
          filters: *integration-master_filters

      # ci-docker
      - test:
          name: test-latest-ci-docker-master
          executor: orb-tools/node-cci
          filters: *integration-master_filters

      - test:
          name: test-older-ci-docker-master
          executor: orb-tools/node-cci
          firefox-version: "62.0.2"
          geckodriver-version: v0.18.0
          filters: *integration-master_filters

      # new ci-docker
      - test:
          name: test-latest-cimg-master
          executor: orb-tools/ubuntu
          filters: *integration-master_filters

      - test:
          name: test-older-cimg-master
          executor: orb-tools/ubuntu
          firefox-version: "62.0.2"
          geckodriver-version: v0.18.0
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/browser-tools
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/browser-tools
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/browser-tools
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
